spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/company-management
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  liquibase:
    enabled: true